Do not generate taxid_map file when reformatting non_parse_seqids db
The reason is, we get taxid_map file in the following format:

gnl|BL_ORD_ID|0 0
gnl|BL_ORD_ID|1 0

And using the above taxid_map file with the -taxid_map option
of makeblastdb results in the following error message:

Error: [makeblastdb] No sequences matched any of the taxids provided

The error does not cause any problem - databases are reformatted and
work just fine. However, seeing an error message like that sure can
make one uneasy.

Signed-off-by: Anurag Priyam <anurag08priyam@gmail.com>